version: 2

sources:
  - name: project_tmob2514
    schema: project_tmob2514
    tables:
      - name: report_cbs_in_footprint
        identifier: report_cbs_in_footprint
      - name: i3_penetration_cbs_normal_10132025
        identifier: i3_penetration_cbs_normal_10132025
      - name: i3_penetration_cbs_excluding_tmo_as_comp_normal_10132025
        identifier: i3_penetration_cbs_excluding_tmo_as_comp_normal_10132025
      - name: i3_penetration_cbs_uplift_v2_10132025
        identifier: i3_penetration_cbs_uplift_v2_10132025
      - name: base_precisely_locations_in_fpt_cbs
        identifier: base_precisely_locations_in_fpt_cbs
      - name: report_cbs_in_intrepid_polygon_footprint
        identifier: report_cbs_in_intrepid_polygon_footprint
      - name: i3_intrepid_census_block_pen_model_0_60_month_10142025
        identifier: i3_intrepid_census_block_pen_model_0_60_month_10142025
      - name: i3_intrepid_census_block_pen_model_w_tmo_0_60_month_10142025
        identifier: i3_intrepid_census_block_pen_model_w_tmo_0_60_month_10142025
      - name: i3_intrepid_full_state_counts
        identifier: i3_intrepid_full_state_counts
      - name: i3_intrepid_cb_address_view_residential
        identifier: i3_intrepid_cb_address_view_residential
  - name: report_acs
    schema: report_acs
    tables:
        - name: fact_acs_2023_census_block_demographics
          identifier: fact_acs_2023_census_block_demographics
        - name: fact_acs_2023_census_block_group_demographics
          identifier: fact_acs_2023_census_block_group_demographics
        - name: fact_acs_2016_census_block_demographics
          identifier: fact_acs_2016_census_block_demographics
  - name: report_bdc
    schema: report_bdc
    tables: 
      - name: fact_bdc_location_reporting_current
        identifier: fact_bdc_location_reporting_current
      - name: nbm_broadband_current_residential_census_block_level
        identifier: nbm_broadband_current_residential_census_block_level
      - name: nbm_broadband_current_residential_census_block_hocofinal_level
        identifier: nbm_broadband_current_residential_census_block_hocofinal_level
  - name: report_market
    schema: report_market
    tables:
      - name: market_crosswalk_latest
        identifier: market_crosswalk_latest
  - name: source_household
    schema: source_household
    tables:
      - name: infousa_2025
        identifier: infousa_2025
  - name: source_market
    schema: source_market
    tables:
      - name: road_miles_by_census_block_group_2024
        identifier: road_miles_by_census_block_group_2024
      - name: road_miles_by_census_block_group_2023
        identifier: road_miles_by_census_block_group_2023
      - name: census_block_2010_to_census_block_2020_proportional
        identifier: census_block_2010_to_census_block_2020_proportional
  - name: source_bdc
    schema: source_bdc
    tables:
      - name: fact_bdc_location_reporting_hocofinal_2023_06
        identifier: fact_bdc_location_reporting_hocofinal_2023_06
      - name: fact_bdc_location_reporting_hocofinal
        identifier: fact_bdc_location_reporting_hocofinal
      - name: fact_bdc_location_reporting_hocofinal_2024_06
        identifier: fact_bdc_location_reporting_hocofinal_2024_06
      - name: fact_bdc_location_reporting_hocofinal_2023_12
        identifier: fact_bdc_location_reporting_hocofinal_2023_12
      - name: fact_bdc_location_reporting_hocofinal_2022_12
        identifier: fact_bdc_location_reporting_hocofinal_2022_12
      - name: fact_bdc_location_reporting_hocofinal_2022_06
        identifier: fact_bdc_location_reporting_hocofinal_2022_06
  - name: report_business
    schema: report_business
    tables:
      - name: fact_businesses_2025
        identifier: fact_businesses_2025
  - name: project_tmob2513
    schema: project_tmob2513
    tables:
      - name: tag_cb_to_polygons
        identifier: tag_cb_to_polygons
      - name: expansion_market_cbs_from_tiger
        identifier: expansion_market_cbs_from_tiger
      - name: report_cbs_in_footprint
        identifier: report_cbs_in_footprint
      - name: report_cbs_in_footprint_by_zip
        identifier: report_cbs_in_footprint_by_zip
      - name: source_acs_tract_language_spoken_at_home_2023
        identifier: source_acs_tract_language_spoken_at_home_2023
      - name: gns_cb_level_penetration_expectations_08192025_v1
        identifier: gns_cb_level_penetration_expectations_08192025_v1
      - name: gns_census_block_pen_model_0_60_month_08202025
        identifier: gns_census_block_pen_model_0_60_month_08202025
      - name: expansion_markets_geoms_union
        identifier: expansion_markets_geoms_union
      - name: report_cbs_in_expansion
        identifier: report_cbs_in_expansion
      - name: source_projected_pen_expansion_20250902
        identifier: source_projected_pen_expansion_20250902
      - name: base_precisely_locations_in_fpt_cbs
        identifier: base_precisely_locations_in_fpt_cbs
      - name: fiber_miles_by_provider_morphology
        identifier: fiber_miles_by_provider_morphology
      - name: source_model_terminal_for_expansion_states_gns_0909
        identifier: source_model_terminal_for_expansion_states_gns_0909
      - name: expansion_market_phase2_mapping
        identifier: expansion_market_phase2_mapping
      - name: tiger_2024_cousub_extract
        identifier: tiger_2024_cousub_extract
      - name: precisely_full_state_data_20250922
        identifier: precisely_full_state_data_20250922
      - name: report_cbs_in_phase_2
        identifier: report_cbs_in_phase_2


  
